version: '3.8'

services:
  app:
    build:
      context: ./php
    container_name: barber_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - barber-network
    depends_on:
      - db

  web:
    image: nginx:latest
    container_name: barber_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    networks:
      - barber-network

  db:
    image: mysql:8.0
    container_name: barber_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: barber
      MYSQL_USER: barberuser
      MYSQL_PASSWORD: barberpass
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - barber-network

volumes:
  dbdata:

networks:
  barber-network:
    driver: bridge
